# 端口号
server:
  port: 8081

# 日志
logging:
  level:
    com.summer: debug

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/summer
    username: root
    password: root

# mybatis
mybatis:
  type-aliases-package: com.summer.pojo
